const express = require('express');
const router = express.Router();
const controller = require('../controllers/classify');

router.get('/thethaomuahe', controller.thethaomuahe);
router.get('/thethaomuadong', controller.thethaomuadong);
router.get('/trangphucnu', controller.trangphucnu);
router.get('/trangsucnu', controller.trangsucnu);
router.get('/giaynu', controller.giaynu);
router.get('/trangphucnam', controller.trangphucnam);
router.get('/trangsucnam', controller.trangsucnam);
router.get('/giaynam', controller.giaynam);
router.get('/banchaynhat', controller.banchaynhat);
router.get('/Prada', controller.Prada);
router.get('/Salvatoreferragamo', controller.Salvatoreferragamo);
router.get('/Fendi', controller.Fendi);
router.get('/Givenchy', controller.Givenchy);
router.get('/search', controller.search);
router.get('/price_1', controller.price_1);
router.get('/price_2',controller.price_2);
router.get('/price_3', controller.price_3);
module.exports = router;